from __future__ import annotations

import csv
import json
import logging
import re
from pathlib import Path

from jinja2 import Template

from .models import ReleaseDefinition

logger = logging.getLogger("adogap")

_SLUG_RE = re.compile(r"[^a-zA-Z0-9._-]+")


def slugify(name: str) -> str:
    """GitHub environment names allow most characters, but keep this
    conservative and predictable for scripting/branch-policy purposes."""
    return _SLUG_RE.sub("-", name.strip()).strip("-").lower()


_APPLY_SCRIPT_TEMPLATE = Template(
    """#!/usr/bin/env bash
# Generated by adogap scaffold — review before running.
# Creates/updates GitHub Environments with protection rules equivalent to
# the approvals and (where mappable) gates found in the source ADO release
# pipeline "{{ release_name }}" (definition id {{ release_id }}).
#
# PREREQUISITES:
#   - gh CLI authenticated with a token that has 'repo' + admin rights on
#     the target repository (environment protection rules are an admin API).
#   - reviewer-mapping.csv filled in with real GitHub usernames — this
#     script will fail loudly if any mapping is still blank.
#   - Deployment gates are NOT auto-applied here (see gates-checklist.md);
#     GitHub Actions has no direct gate equivalent, they must be rebuilt as
#     required status checks, custom deployment protection rules, or
#     workflow-level checks.

set -euo pipefail

REPO="{{ '${1:?Usage: create-environments.sh <owner/repo>}' }}"
MAPPING_FILE="$(dirname "$0")/reviewer-mapping.csv"

if grep -q ",$" "$MAPPING_FILE" 2>/dev/null; then
    echo "ERROR: reviewer-mapping.csv has unfilled GitHub username(s). Fill every row before running this script." >&2
    exit 1
fi

lookup_github_user() {
    local ado_identity="$1"
    awk -F',' -v key="$ado_identity" '$1 == key { print $3; exit }' "$MAPPING_FILE"
}

{% for env in environments %}
echo "=== Creating/updating environment: {{ env.name }} ==="
{% if env.reviewer_identities %}
REVIEWERS=()
{% for identity in env.reviewer_identities %}
GH_USER_{{ loop.index }}=$(lookup_github_user "{{ identity }}")
if [ -z "${GH_USER_{{ loop.index }}}" ]; then
    echo "ERROR: no GitHub username mapped for ADO identity '{{ identity }}' in reviewer-mapping.csv" >&2
    exit 1
fi
REVIEWERS+=("$GH_USER_{{ loop.index }}")
{% endfor %}
REVIEWER_JSON=$(printf '%s\\n' "${REVIEWERS[@]}" | jq -R . | jq -s '[.[] | {type:"User", id: .}]')
{% else %}
REVIEWER_JSON='[]'
{% endif %}

gh api \\
  --method PUT \\
  -H "Accept: application/vnd.github+json" \\
  "/repos/$REPO/environments/{{ env.slug }}" \\
  -f "wait_timer={{ env.wait_timer_minutes }}" \\
  -F "reviewers=${REVIEWER_JSON}" \\
  -f "deployment_branch_policy[protected_branches]=false" \\
  -f "deployment_branch_policy[custom_branch_policies]=true"

echo "  -> {{ env.slug }} done ({{ env.reviewer_identities|length }} reviewer(s), {{ env.wait_timer_minutes }}min wait timer)"
{% endfor %}

echo ""
echo "Environments created. Remaining manual work:"
echo "  1. Review gates-checklist.md — deployment gates have no direct equivalent."
echo "  2. Populate secrets in each environment from secrets-checklist.md (values must be re-entered, never auto-migrated)."
echo "  3. Apply OIDC federated credentials from oidc-federated-credentials.json via Azure CLI or Terraform."
"""
)


def generate_environment_config(release_def: ReleaseDefinition) -> list[dict]:
    """Builds the structured environment definitions used both for the JSON
    artifact and the apply-script template."""
    environments = []
    for stage in release_def.stages:
        reviewer_identities = []
        wait_timer = 0

        if stage.pre_approvals:
            reviewer_identities.extend(
                a.unique_name or a.display_name for a in stage.pre_approvals.approvers
            )
            if stage.pre_approvals.timeout_minutes:
                wait_timer = max(wait_timer, 0)  # timeout != wait timer; approvals map to reviewers, not wait_timer

        environments.append(
            {
                "name": stage.name,
                "slug": slugify(stage.name),
                "reviewer_identities": sorted(set(reviewer_identities)),
                "wait_timer_minutes": wait_timer,
                "gate_count": len(stage.gates),
                "service_connection_ids": [sc.id for sc in stage.service_connections],
                "variable_group_ids": [vg.id for vg in stage.variable_groups],
            }
        )
    return environments


def generate_oidc_federated_credentials(release_def: ReleaseDefinition, github_org: str, repo_name: str) -> list[dict]:
    """
    Generates federated credential definitions for each unique service
    connection, following the standard OIDC subject-claim pattern for
    environment-scoped workflows:
        repo:{org}/{repo}:environment:{environment_name}
    These are templates to review and apply via `az ad app federated-credential
    create` or your Terraform/Bicep module — adogap does not call Azure APIs.
    """
    seen_connections: set[str] = set()
    credentials = []

    for stage in release_def.stages:
        for sc in stage.service_connections:
            key = f"{sc.id}:{stage.name}"
            if key in seen_connections:
                continue
            seen_connections.add(key)
            credentials.append(
                {
                    "source_ado_service_connection_id": sc.id,
                    "source_ado_service_connection_type": sc.connection_type or "unknown (verify manually)",
                    "environment": stage.name,
                    "federated_credential_name": f"gha-{slugify(repo_name)}-{slugify(stage.name)}",
                    "subject": f"repo:{github_org}/{repo_name}:environment:{slugify(stage.name)}",
                    "issuer": "https://token.actions.githubusercontent.com",
                    "audience": "api://AzureADTokenExchange",
                    "azure_cli_command_template": (
                        f"az ad app federated-credential create --id <APP_OBJECT_ID> --parameters "
                        f'\'{{"name":"gha-{slugify(repo_name)}-{slugify(stage.name)}",'
                        f'"issuer":"https://token.actions.githubusercontent.com",'
                        f'"subject":"repo:{github_org}/{repo_name}:environment:{slugify(stage.name)}",'
                        f'"audiences":["api://AzureADTokenExchange"]}}\''
                    ),
                }
            )
    return credentials


def generate_reviewer_mapping_csv(environments: list[dict], output_path: Path) -> None:
    """
    ADO approvers are identified by AD identity (email/UPN) — there is no
    safe automated way to resolve that to a GitHub username without a
    directory lookup adogap doesn't have access to. This writes a template
    for a human to fill in; the apply script refuses to run until every row
    has a github_username value.
    """
    all_identities = sorted({identity for env in environments for identity in env["reviewer_identities"]})

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["ado_identity", "display_name", "github_username"])
        for identity in all_identities:
            writer.writerow([identity, "", ""])  # third column intentionally blank for human fill-in


def generate_secrets_checklist(release_def: ReleaseDefinition) -> str:
    lines = ["# Secrets checklist\n", (
        "Variable group values are **never** read or exported by adogap — "
        "ADO does not expose secret variable values via the read-only API "
        "scopes this tool uses, and even if it did, piping secret values "
        "through a migration tool is bad practice. Re-enter each of these "
        "directly into the corresponding GitHub Environment's secrets, "
        "sourced from your secrets vault / ADO variable group UI.\n"
    )]

    for stage in release_def.stages:
        if not stage.variable_groups:
            continue
        lines.append(f"\n## Environment: {stage.name}\n")
        for vg in stage.variable_groups:
            lines.append(f"- Variable group ID `{vg.id}`{f' ({vg.name})' if vg.name else ''} — "
                          f"open in ADO (Pipelines > Library) and recreate each variable as a "
                          f"GitHub Environment secret or variable, matching secret/non-secret status.")
    return "\n".join(lines)


def generate_gates_checklist(release_def: ReleaseDefinition) -> str:
    lines = [
        "# Deployment gates checklist\n",
        "GitHub Actions has no direct equivalent to ADO deployment gates "
        "(automated pre/post checks like Invoke REST API, Azure Monitor "
        "alerts, or Azure Function checks that must pass before/after a "
        "deployment proceeds, independent of human approval). Each one "
        "below needs a manual redesign choice:\n",
        "- **Simple pass/fail HTTP check** -> a workflow step that curls the "
        "endpoint and fails the job on non-2xx, placed before/after the "
        "deploy step.\n",
        "- **Requires waiting/polling** -> a required status check from an "
        "external system, or a custom GitHub deployment protection rule "
        "(https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/create-custom-protection-rules).\n",
        "- **Azure Monitor alert gate** -> custom protection rule backed by "
        "an Azure Function or Action that queries Azure Monitor.\n",
    ]

    any_gates = False
    for stage in release_def.stages:
        if not stage.gates:
            continue
        any_gates = True
        lines.append(f"\n## Environment: {stage.name}\n")
        for gate in stage.gates:
            lines.append(f"- **{gate.name}** ({gate.kind}-deployment, task type: `{gate.task_type or 'unknown'}`)")

    if not any_gates:
        lines.append("\nNo deployment gates found in this release definition.\n")

    return "\n".join(lines)


def render_apply_script(release_def: ReleaseDefinition, environments: list[dict]) -> str:
    return _APPLY_SCRIPT_TEMPLATE.render(
        release_name=release_def.name,
        release_id=release_def.id,
        environments=environments,
    )


def scaffold(release_def: ReleaseDefinition, github_org: str, repo_name: str, output_dir: Path) -> dict[str, Path]:
    """Runs the full scaffolding step and writes all artifacts to output_dir.
    Returns a dict of artifact name -> path for reporting."""
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts: dict[str, Path] = {}

    environments = generate_environment_config(release_def)
    env_path = output_dir / "environments.json"
    env_path.write_text(json.dumps(environments, indent=2), encoding="utf-8")
    artifacts["environments"] = env_path

    oidc_creds = generate_oidc_federated_credentials(release_def, github_org, repo_name)
    oidc_path = output_dir / "oidc-federated-credentials.json"
    oidc_path.write_text(json.dumps(oidc_creds, indent=2), encoding="utf-8")
    artifacts["oidc_credentials"] = oidc_path

    mapping_path = output_dir / "reviewer-mapping.csv"
    generate_reviewer_mapping_csv(environments, mapping_path)
    artifacts["reviewer_mapping"] = mapping_path

    secrets_path = output_dir / "secrets-checklist.md"
    secrets_path.write_text(generate_secrets_checklist(release_def), encoding="utf-8")
    artifacts["secrets_checklist"] = secrets_path

    gates_path = output_dir / "gates-checklist.md"
    gates_path.write_text(generate_gates_checklist(release_def), encoding="utf-8")
    artifacts["gates_checklist"] = gates_path

    script_path = output_dir / "create-environments.sh"
    script_path.write_text(render_apply_script(release_def, environments), encoding="utf-8")
    script_path.chmod(0o755)
    artifacts["apply_script"] = script_path

    logger.info("Scaffolding written to %s (%d environment(s))", output_dir, len(environments))
    return artifacts
